apiVersion: container-canary.nvidia.com/v1
kind: Validator
name: example
description: Container Canary CI Example
env: []
ports:
  - port: 5000
    protocol: TCP
volumes: []
checks:
  - name: http
    description: Exposes an HTTP interface on port 5000
    probe:
      httpGet:
        path: /foo
        port: 5000
      failureThreshold: 30
  - name: python
    description: Has Python installed
    probe:
      exec:
        command:
          - /bin/sh
          - -c
          - "which python"
