name: ci

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: jacobtomlinson/canary-ci-example:latest
      - name: Install Container Canary
        run: |
          curl -L https://github.com/NVIDIA/container-canary/releases/download/v0.1.1/canary_linux_amd64 > /usr/local/bin/canary
          chmod +x /usr/local/bin/canary
      - name: Validate container
        run: canary validate --file canary-validator.yaml jacobtomlinson/canary-ci-example:latest
